import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import Logo from "../public/imgs/logo.png";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <Link href="/">
            <Image src={Logo} alt="Bookish" width={220} />
          </Link>
          <button className="profile-btn">
            <span>id</span>
          </button>
        </header>
        {children}
      </body>
    </html>
  );
}
